---
- name: Create SSH-Keypair if none exists
  hosts: all
  tasks:
    - name: generate Keypair
      community.crypto.openssh_keypair:
        regenerate: never
        path: ~/.ssh/id_rsa
  tags:
    - ssh

- name: Install Ros2
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - install_humble
  vars:
    ros2_distribution: humble
    ros2_gpg_key_url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
    ros2_repository_url: http://packages.ros.org/ros2/ubuntu
    ros2_configuration: ros-base
    ros2_user:
      name: turtle
      group: turtle
  tags:
    - install_humble
    

- name: Install driving_swarm_infrastructure and requirements
  hosts: all
  gather_facts: yes
  roles:
    - common
  vars:
    ros2_distribution: humble
  tags:
    - common

- name: configure and update turtlebot
  hosts: turtlebot
  gather_facts: yes
  become: yes
  roles:
    - raspy_config
  vars:
    ros2_distribution: humble
  tags:
    - raspy_config