---
# run apt update + apt upgrade
- name: add correct ROS-key
  shell:
    cmd: curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

- name: update packgaes
  apt:
    name: "*"
    state: latest
    update_cache: yes