
- name: set up driving swarm git
  git:
    repo: https://github.com/ovgu-FINken/driving_swarm_infrastructure.git
    dest: ~/driving_swarm_infrastructure
    version: robot-release
    force: yes

- name: rebuild driving_swarm_infrastructure
  shell:
    cmd: |
      . ~/.rosrc
      rm -rf build
      rm -rf install
      colcon build --cmake-clean-cache --parallel-workers 1 --packages-select system_status driving_swarm_messages robot_spawner_pkg
    chdir: ~/driving_swarm_infrastructure
    executable: /usr/bin/bash

- name: reboot
  reboot:
    become: yes
    msg: "Rebooting by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
