---

# set up higher temprature limits to prevent overheating issues
# the raspberry pi reduces its clock speed when it gets too hot which leads to higher load
# -> if we do not rise the temp limit the raspberry pi will often lock up with overheating
- name: configure temp limit
  template:
    src: usercfg.txt.j2
    dest: /boot/firmware/usercfg.txt
  tags: temp_limit

- name: create directory /etc/issue.d
  file:
    path: /etc/issue.d
    state: directory
  tags: autostart

# this will display the ip address on the login screen
- name: setup issues file
  template:
    src: 00_ip.txt.j2
    dest: /etc/issue.d/00_ip.txt
  tags: autostart
    
- name: install launch script    
  template:
    src: core.sh.j2
    dest: /home/turtle/core.sh
    owner: turtle
  tags: autostart

- name: install systemd service
  template:
    src: DrivingSwarmCore.service.j2
    dest: /etc/systemd/system/DrivingSwarmCore.service
  tags: autostart

- name: enable systemd service
  systemd:
    name: DrivingSwarmCore.service
    enabled: yes
    state: started
  tags: autostart

- name: enable zenoh bridge
  systemd:
    name: zenoh-bridge-dds.service
    enabled: yes
    state: started
  tags: autostart, zenoh

# setup distcc on turtlebot
- name: configure distcc
  template:
    src:  distccrc.j2
    dest: /home/turtle/.distccrc
  tags: distcc

# remove snapd to prevent autoupdates that lead to cpu load
- name: Remove snapd from Ubuntu
  apt:
    name: snapd
    state: absent
    purge: yes
  when: ansible_distribution == "Ubuntu"

- name: Remove snapd-related directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /snap
    - /var/snap
    - /var/lib/snapd
    - /home/turtle/snap
  when: ansible_distribution == "Ubuntu"

# remove unattended upgrades to prevent autoupdates that lead to cpu load
- name: remove unattended unattended-upgrades
  apt:
    name: unattended-upgrades
    state: absent
    purge: yes
      

- name: remove old opencr update
  file: 
    path: ~/opencr_update.tar.bz2
    state: absent
  tags: opencr


- name: add libc6 for armhf to dpkg
  shell:
    cmd: dpkg --add-architecture armhf
  tags: opencr

- name: install libc6 for armhf
  apt:
    name: libc6:armhf
    state: present
    update_cache: yes
  tags: opencr
  
- name: opencr update
  shell:
    cmd: |
      wget https://github.com/ROBOTIS-GIT/OpenCR-Binaries/raw/master/turtlebot3/ROS1/latest/opencr_update.tar.bz2
      tar -xvf opencr_update.tar.bz2
      cd opencr_update
      ./update.sh /dev/ttyACM0 burger.opencr
  tags: opencr


- name: install robot_upstart
  apt:
    name: "ros-{{ ros2_distribution }}-robot-upstart"
    state: present

- name: upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes
  tags: upgrade, update


## swapfile for compilation

## checkout tb3 package

## compile tb3 package with colcon build
# MAKEFLAGS="-j1"

- name: reboot
  reboot:
    msg: "Rebooting by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
