---

- name: set hostname
  hostname:
    name: "turtlebot{{ domain_id }}"
  tags: hostname

- name: disable hostname changing of cloud init
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname'
    line: 'preserve_hostname: true'
  tags: hostname

- name: install launch script 
  template:
    src: core.sh.j2
    dest: /home/turtle/core.sh
    owner: turtle
    group: turtle
    mode: 0777
  tags: autostart

- name: install systemd service
  template:
    src: DrivingSwarmCore.service.j2
    dest: /etc/systemd/system/DrivingSwarmCore.service
  tags: autostart

# install systemd service for driving swarm core, but stop it for now
- name: enable systemd service
  systemd:
    name: DrivingSwarmCore.service
    enabled: yes
    state: stopped
  tags:
    - autostart
    - opencr

# set up higher temprature limits to prevent overheating issues
# the raspberry pi reduces its clock speed when it gets too hot which leads to higher load
# -> if we do not rise the temp limit the raspberry pi will often lock up with overheating
- name: configure temp limit
  template:
    src: usercfg.txt.j2
    dest: /boot/firmware/usercfg.txt
  tags: temp_limit


# this will display the ip address on the login screen
- name: display ip in login screen
  lineinfile:
    path: /etc/issue
    line: "IP address: \\4{wlan0}"
  tags: autostart
    
- name: enable zenoh bridge
  systemd:
    name: zenoh-bridge-dds.service
    enabled: yes
    state: started
  tags: autostart, zenoh

# setup distcc on turtlebot
- name: configure distcc
  template:
    src:  distccrc.j2
    dest: /home/turtle/.distccrc
  tags: distcc

# remove snapd to prevent autoupdates that lead to cpu load
- name: Remove snapd from Ubuntu
  apt:
    name: snapd
    state: absent
    purge: yes
  when: ansible_distribution == "Ubuntu"

- name: Remove snapd-related directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /snap
    - /var/snap
    - /var/lib/snapd
    - /home/turtle/snap
  when: ansible_distribution == "Ubuntu"

# remove unattended upgrades to prevent autoupdates that lead to cpu load
- name: remove unattended unattended-upgrades
  apt:
    name: unattended-upgrades
    state: absent
    purge: yes
      

- name: add libc6 for armhf to dpkg
  shell:
    cmd: dpkg --add-architecture armhf
  tags: opencr

- name: install libc6 for armhf
  apt:
    name: libc6:armhf
    state: present
    update_cache: yes
  tags: opencr
  
- name: opencr update
  shell:
    cmd: |
      rm -rf opencr_update*
      wget https://github.com/ROBOTIS-GIT/OpenCR-Binaries/raw/master/turtlebot3/ROS2/latest/opencr_update.tar.bz2
      tar -xvf opencr_update.tar.bz2
      cd opencr_update
      ./update.sh /dev/ttyACM0 burger.opencr
  tags: opencr

- name: install telegraf
  apt:
    name: telegraf
    state: present
  tags: telegraf

# generate config with 
# telegraf config --input-filter cpu:mem:swap:net:system --output-filter influxdb --section-filter agent:global_tags:inputs:outputs > roles/raspy_config/templates/telegraf.conf.j2
# and modify
# 
# possibly useful: chrony, wireless, ping

- name: install telegraf config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  tags: telegraf

- name: enable telegraf
  systemd:
    name: telegraf.service
    enabled: yes
    state: started
  tags: telegraf

- name: upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes
  tags: upgrade, update

- name: reboot
  reboot:
    msg: "Rebooting by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  tags: reboot
