---

# set up higher temprature limits to prevent overheating issues
# the raspberry pi reduces its clock speed when it gets too hot which leads to higher load
# -> if we do not rise the temp limit the raspberry pi will often lock up with overheating
- name: configure temp limit
  template:
    src: usercfg.txt.j2
    dest: /boot/firmware/usercfg.txt
    
# setup bash config for ros
- name: configure rosrc
  template:
    src: rosrc.j2
    dest: /home/turtle/.rosrc
    
# set autostart script for ros
- name: copy autostart.bash
  template:
    src: autostart.bash.j2
    dest: /home/turtle/autostart.bash
    
# setup distcc on turtlebot
- name: configure distcc
  template:
    src:  distccrc.j2
    dest: /home/turtle/.distccrc

# setup bash config for ros
- name: configure bashrc
  template:
    src: bashrc.j2
    dest: /home/turtle/.bashrc

# remove snapd to prevent autoupdates that lead to cpu load
- name: Remove snapd from Ubuntu
  apt:
    name: snapd
    state: absent
    purge: yes
  when: ansible_distribution == "Ubuntu"

- name: Remove snapd-related directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /snap
    - /var/snap
    - /var/lib/snapd
    - /home/turtle/snap
  when: ansible_distribution == "Ubuntu"

# remove unattended upgrades to prevent autoupdates that lead to cpu load
- name: remove unattended unattended-upgrades
  apt:
    name: unattended-upgrades
    state: absent
    purge: yes
  
- name: opencr update
  shell:
    cmd: |
      rm -rf ./opencr_update.tar.bz2
      wget https://github.com/ROBOTIS-GIT/OpenCR-Binaries/raw/master/turtlebot3/ROS1/latest/opencr_update.tar.bz2
      tar -xvf opencr_update.tar.bz2
      cd opencr_update
      ./update.sh /dev/ttyACM0 burger.opencr
  tags: opencr




- name: reboot
  reboot:
    msg: "Rebooting by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami