---
- name: install chrony
  become: yes
  apt:
    name: chrony
    state: present
  tags:
    - chrony

- name: configure chrony config
  become: yes
  template: 
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
  notify: restart chrony
  tags:
    - chrony

- name: start chrony
  become: yes
  service:
    name: chrony
    state: started
    enabled: yes
  tags:
    - chrony
      
- name: install pip and other python packages
  become: yes
  apt:
    name: 
      - python3-pip
      - python3-vcstool
      - python3-skimage
      - python3-shapely
      - python3-termcolor
      - python3-rosdep2
      - python3-colcon-common-extensions
      - tmux
      - vim
      - htop
    state: present
      
- name: pip requirements
  become: yes
  pip:
    name:
      #- git+https://github.com/ghliu/pyReedsShepp.git
      - deprecation
      #- dubins
      #- bezier


- name: set up driving swarm git
  git:
    repo: https://github.com/ovgu-FINken/driving_swarm_infrastructure.git
    dest: ~/ros/driving_swarm_infrastructure
    version: master


- name: configure .rosrc
  template: 
    src: rosrc.j2
    dest: ~/.rosrc

- name: add rosrc to bashrc
  lineinfile:
    path: ~/.bashrc
    line: source ~/.rosrc

#- name: create directory for dependencies workspace
#  file:
#    path: ~/ros/dependencies/src
#    state: directory      
#      - name: setup dependencies workspace
#        shell:
#          vcs import --input https://raw.githubusercontent.com/ovgu-FINken/driving_swarm_infrastructure/master/repo-files/turtlebot3.repos ~/ros/dependencies/src/
#      
#          
#      - name: build dependencies
#        shell:
#          cmd: |
#            colcon build
#          chdir: ~/ros/dependencies
#          executable: /usr/bin/bash
#        tags:
#          - colcon
#            
#      - name: add dependencies to rosrc
#        lineinfile:
#          path: ~/.rosrc
#          line: source ~/ros/dependencies/install/setup.bash
#        tags:
#          - colcon
      
- name: rosdep install
  shell: |
    source ~/.bashrc
    rosdep update --rosdistro humble
    rosdep install --rosdistro humble --from-paths ~/ros/driving_swarm_infrastructure/src/ -y --ignore_src
  tags:
    - rosdep
      
- name: build driving swarm
  shell:
    cmd: |
      . ~/.bashrc && colcon build
    chdir: ~/ros/driving_swarm_infrastructure
    executable: /usr/bin/bash 
  tags:
    - colcon

- name: add driving_swarm_infrastructure to rosrc
  lineinfile:
    path: ~/.rosrc
    line: source ~/ros/driving_swarm_infrastructure/install/local_setup.bash
  tags:
    - colcon
