---

- name: stop driving swarm service
  service:
    name: DrivingSwarmCore
    state: stopped
    enabled: yes
  tags:
    - stop
      
- name: stop zenoh-bridge-dds.service
  service:
    name: zenoh-bridge-dds.service
    state: stopped
    enabled: yes
  tags:
    - stop
    
- name: start zenoh-bridge-dds.service
  service:
    name: zenoh-bridge-dds.service
    state: started
    enabled: yes
  tags:
    - start

- name: start driving swarm service
  service:
    name: DrivingSwarmCore
    state: started
    enabled: yes
  tags:
    - start

## reboot the turtlebots
- name: reboot turtlebots
  reboot:
    msg: "Rebooting by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  tags: 
    - reboot